"""update_trans

Revision ID: 55d9aaf3b9e4
Revises: 3f3c36447a93
Create Date: 2022-11-11 00:51:34.895930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d9aaf3b9e4'
down_revision = '3f3c36447a93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
