"""small_fix

Revision ID: f06e845db821
Revises: ff8ac8d77bc1
Create Date: 2022-11-11 00:31:52.455176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06e845db821'
down_revision = 'ff8ac8d77bc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Transactions', 'wallet_id_2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Transactions', 'Wallets', ['wallet_id_2'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.alter_column('Transactions', 'wallet_id_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
